# Generated by Django 5.2 on 2025-04-17 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockentries'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockBunches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stockEntries_id', models.ManyToManyField(related_name='stockBunches', to='stocks.stockentries')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
