# Generated by Django 5.2 on 2025-04-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stockbunches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
        migrations.RenameModel(
            old_name='stockBunches',
            new_name='stockBunch',
        ),
        migrations.RenameModel(
            old_name='stockEntries',
            new_name='stockEntry',
        ),
    ]
