# Generated by Django 5.2 on 2025-04-17 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_products_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbunch',
            name='stockEntries_id',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='stockBunch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stockbunch'),
        ),
    ]
