# Generated by Django 5.1.1 on 2025-04-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_stockbunch_stockentries_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='product_name',
        ),
    ]
